- project:
    check:
      jobs:
        - nebulous-library-template-build-java-libraries
        - nox-linters
    gate:
      jobs:
        - nebulous-library-template-upload-java-libraries
        - nox-linters
    promote:
      jobs:
        - nebulous-library-template-promote-java-libraries
